// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS4NMZob5rkWaJQaJmzmk4fPj22Q8PnQo',
    appId: '1:537747327325:web:13caef0a3f2d90339b00b4',
    messagingSenderId: '537747327325',
    projectId: 'ticketeve-user',
    authDomain: 'ticketeve-user.firebaseapp.com',
    storageBucket: 'ticketeve-user.firebasestorage.app',
    measurementId: 'G-C99TFQYN7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChLKyEx5hMl9Us2bVFwaz0ohItoq0P0qY',
    appId: '1:537747327325:android:126a026a02ed19ce9b00b4',
    messagingSenderId: '537747327325',
    projectId: 'ticketeve-user',
    storageBucket: 'ticketeve-user.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWAg2MN_Rt2efTP7QZAiNnNE5vhiJjWrI',
    appId: '1:537747327325:ios:f326fb52f12231509b00b4',
    messagingSenderId: '537747327325',
    projectId: 'ticketeve-user',
    storageBucket: 'ticketeve-user.firebasestorage.app',
    iosBundleId: 'com.example.eventrightProUser',
  );
}
