// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB49XNKO9PUV4twDFvxjtOhlbX9veh-Oh0',
    appId: '1:412923263237:web:cac6f66f4498372cc7df6c',
    messagingSenderId: '412923263237',
    projectId: 'ticketeve-organizer',
    authDomain: 'ticketeve-organizer.firebaseapp.com',
    storageBucket: 'ticketeve-organizer.firebasestorage.app',
    measurementId: 'G-9YCYL59TSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjZfp28-ORqT8esug74u29y43m7P3GiA0',
    appId: '1:412923263237:android:5eeffc85dbb35ea1c7df6c',
    messagingSenderId: '412923263237',
    projectId: 'ticketeve-organizer',
    storageBucket: 'ticketeve-organizer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASaRbN-Mlj6n6OuaqhvwCLzIq5AW57y5w',
    appId: '1:412923263237:ios:84b6034d5f94f57ec7df6c',
    messagingSenderId: '412923263237',
    projectId: 'ticketeve-organizer',
    storageBucket: 'ticketeve-organizer.firebasestorage.app',
    iosBundleId: 'com.example.eventrightOrganizer',
  );
}
